apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: node:15.12.0-alpine3.13
    name: node
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: curlimages/curl:7.75.0
    name: curl
  restartPolicy: Never