version: '3'
services:
  postgres:
    image: mattermost/mattermost-preview
    container_name: mattermost-preview
    ports:
      - 8065:8065
    volumes:
      - ./mattermost-data:/mm/mattermost/mattermost-data
      - ./mysql:/var/lib/mysql
