version: '3'
services:
  chat:
    image: mattermost/mattermost-preview
    container_name: mattermost-preview
    ports:
      - 8065:8065
    volumes:
      - ./mattermost-data:/mm/mattermost/mattermost-data
      - ./mysql:/var/lib/mysql
      - ./script:/opt/stub_server/script
