# release-cli Docker image must be specified.

release-job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
  - echo 'release job'
  release:
    tag_name: $CI_COMMIT_TAG
    ref: $CI_COMMIT_TAG
    description: 'release-job'
    
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - sleep
    - "3600"
    lifecycle:
      postStart:
        exec:
          # command: ["/bin/sh", "-c", "sleep 3600"]# infinite roop
          command: ["/bin/sh", "-c", "sleep 3600 &"]
    image: busybox
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}